# Generated by Django 4.1.2 on 2023-01-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('purchase', '0001_initial'),
        ('category', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('base_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            options={
                'db_table': 'stamp_types',
            },
        ),
        migrations.CreateModel(
            name='StampPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.FloatField()),
                ('initial_code', models.CharField(max_length=10)),
                ('series_end', models.BigIntegerField()),
                ('series_start', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
                ('stamp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamp.stamptype')),
            ],
            options={
                'db_table': 'stamp_purchases',
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('sold', models.BooleanField(default=False)),
                ('base_amount', models.FloatField(default=0)),
                ('additional_amount', models.FloatField(default=0)),
                ('title', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='stamp_files/')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('paid_with', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
                ('stamp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamp.stamptype')),
            ],
            options={
                'db_table': 'stamps',
            },
        ),
    ]
