# Generated by Django 4.1.2 on 2023-01-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamppurchase',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
