# Generated by Django 4.1.2 on 2023-01-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0002_stamppurchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamppurchase',
            name='series_start',
            field=models.BigIntegerField(),
        ),
    ]
