# Generated by Django 4.1.2 on 2023-01-31 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0004_stamp_code_stamp_code_number_alter_stamp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='StampPurchase',
        ),
    ]
