# Generated by Django 4.1.2 on 2023-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0005_remove_stamp_purchase_delete_stamppurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
