# Generated by Django 4.1.2 on 2023-03-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0006_stamp_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
