# Generated by Django 4.1.2 on 2023-03-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0007_stamp_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='corresponding_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
