# Generated by Django 4.1.2 on 2023-01-31 04:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0005_remove_stamp_purchase_delete_stamppurchase'),
        ('location', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='balance',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='time',
        ),
        migrations.AddField(
            model_name='purchase',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='series_end',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='series_start',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stamp_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stamp.stamptype'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
