# Generated by Django 4.1.2 on 2023-01-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhaar',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
